### ISSUE TITLE
� character in output csv data

### ISSUE THREAD

**Issue by AMO-MTSY** [htmlburger/carbon-csv#3]
Hi,
é are transformed to � .
How can i solve this?

**Comment by AMO-MTSY** [comment]
src\CsvFile.php
	const DEFAULT_ENCODING = 'utf-8';
	private $encoding = 'ISO-8859-1';

Solves the problem

**Comment by ppetrov2create** [comment]
Sorry for the late reply.

Thank you for bringing this up :)

The library needs to "know" the encoding of the file, so it can properly convert it to utf8.

You can use `set_encoding` to set the encoding. Here's an example:

```
$csv = new CsvFile('filename.csv');
$csv->set_encoding('ISO-8859-1');
```

The readme has been updated with an [example](https://github.com/htmlburger/carbon-csv#set_encodingencoding) for said method.

**Comment by AMO-MTSY** [comment]
Thank you for your prompt reply
